# Workflow name
name: 'Publish'

# Event for the workflow
on:
  push:
    branches:
      - main
      - 'feature/**'
      - '*fix/**'

# List of jobs
jobs:
  publish-package:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm install
      # - name: Unit tests
      #   run: npm run test
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Build
        run: npm run build
      - name: Copy dist directory
        run: cp -r dist/* .
      # - name: Upload dist folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dist
      #     path: dist
      - name: Publish from main
        run: npm publish
        if: github.ref == 'refs/heads/main'
        working-directory: 'dist'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      # - name: Publish beta version
      #   run: npm publish --tag next
      #   if: (contains(github.ref, 'feature') || contains(github.ref, 'fix')) && contains(steps.package-version.outputs.current-version, 'beta')
      #   working-directory: 'dist'
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
